from flask import Flask, render_template, jsonify, request
from flask_socketio import SocketIO, emit

from models import (
    init_db,
    clear_alerts,
    get_last_alerts,
    update_device,
    log_alert,
    get_devices,
    get_alert_stats,
    increment_device_alert_count,
)

app = Flask(__name__)
app.config["SECRET_KEY"] = "cybersecurity-demo"

socketio = SocketIO(app, cors_allowed_origins="*", async_mode="threading")

# Initialize database on startup
init_db()
clear_alerts()


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/alerts")
def api_alerts():
    """New: JSON endpoint so alerts can be pulled by other tools/scripts."""
    limit = int(request.args.get("limit", 50))
    return jsonify(get_last_alerts(limit))


@app.route("/api/devices")
def api_devices():
    """New: JSON endpoint listing known devices and their alert counts."""
    return jsonify(get_devices())


@app.route("/api/stats")
def api_stats():
    """New: alert counts grouped by severity, for a dashboard summary bar."""
    return jsonify(get_alert_stats())


@socketio.on("connect")
def handle_connect():
    print("[Web] Client connected")

    # Send initial data to dashboard
    emit("load_alerts", get_last_alerts(20))
    emit("devices_list", get_devices())
    emit("stats_update", get_alert_stats())


@socketio.on("request_devices")
def handle_device_request():
    """
    Sends updated device list when frontend requests it
    """
    emit("devices_list", get_devices())


@socketio.on("submit_alert")
def handle_submit_alert(data):
    """
    BUGFIX (architecture): detector.py and simulator.py used to run as
    separate Python processes that did `from server import receive_new_alert`.
    That import re-executes server.py in a brand new process, creating an
    isolated Flask/SocketIO app that is never connected to the actual
    running dashboard - so alerts generated by those scripts silently
    vanished and never reached a browser.

    They now connect to this server as real Socket.IO *clients* (see
    detector.py / simulator.py, which use socketio.Client()) and emit a
    "submit_alert" event over the network/socket, which arrives here -
    in the one process that's actually serving the dashboard - and gets
    broadcast for real.
    """
    src_ip = data.get("src_ip", "unknown")
    alert_type = data.get("type", "UNKNOWN")
    detail = data.get("detail", "")
    severity = data.get("severity", "MEDIUM")

    receive_new_alert(src_ip, alert_type, detail, severity)


def receive_new_alert(src_ip, alert_type, detail, severity="MEDIUM"):
    """
    Central event handler for all IDS alerts (simulated or from the live
    detector). Also callable in-process, e.g. from a background task.
    """
    # Store alert in database
    log_alert(src_ip, alert_type, detail, severity)

    # Update device last seen time + running alert count
    update_device(src_ip)
    increment_device_alert_count(src_ip)

    payload = {
        "src_ip": src_ip,
        "type": alert_type,
        "detail": detail,
        "severity": severity,
    }

    # Broadcast to all connected dashboard clients
    socketio.emit("display_alert", payload)
    socketio.emit("stats_update", get_alert_stats())


if __name__ == "__main__":
    print("[System] Starting Cyber Security Dashboard...")
    print("[System] Dashboard: http://localhost:5000")
    print("[System] In another terminal, run: python simulator.py  (safe, synthetic demo traffic)")
    print("[System] Or (needs admin/root):     python detector.py  (real packet sniffing)")
    socketio.run(app, host="0.0.0.0", port=5000)
